#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv ufw shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Open bin scripts
se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}

# Colorize commands when possible.
alias \
	ls="ls -lAh --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

alias \
	ytmp3="yt-dlp -x --audio-format mp3 --audio-quality 0" \
	myip="curl ipinfo.io/ip" \
	ports="netstat -tulanp" \
	untar="tar -zxvf" \
	lf="lfub" \
	efile="gpg -c --no-symkey-cache --cipher-algo AES256" \
	estring="openssl enc -e -aes-256-cbc -base64 -pbkdf2" \
	xclip="xclip -sel clip" \
	abook="abook --config "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$XDG_DATA_HOME"/abook/addressbook" \
	mbsync="mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc" \
	config='git --git-dir=$HOME/.local/share/dotfiles --work-tree ~' \
	astylec='astyle --ascii --add-braces --break-one-line-headers --align-pointer=name --pad-comma --unpad-paren --pad-header --pad-oper --max-code-length=132 --convert-tabs --indent=spaces=4 --indent-continuation=1 --indent-switches --lineend=linux --min-conditional-indent=1 --options=none --style=allman' \
