#!/bin/sh

# This file runs when a DM logs you into a graphical session.

xrandr --output VGA-1 --left-of LVDS-1 &
xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
xinput --map-to-output '12' LVDS-1 && xinput --map-to-output '17' LVDS-1 #Calibrating touchscreen
setbg &&		# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources & xrdbpid=$!

autostart="xcompmgr dunst pipewire"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
