#!/bin/sh

# This file runs when a DM logs you into a graphical session.

xinput --map-to-output '12' LVDS-1 & #Calibrating touchscreen
xinput --map-to-output '17' LVDS-1 & #Calibrating touchscreen
xrandr --output VGA-1 --left-of LVDS-1 &
xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources & xrdbpid=$!
